# docker-compose -f docker-compose-1.0.yml up -d
version: '3.8'

services:
  marketing-platform-app:
    image: system/marketing-platform-app:1.0-SNAPSHOT
    container_name: marketing-platform
    restart: on-failure
    ports:
      - "8091:8091"
    environment:
      TZ: Asia/Shanghai
      SERVER_PORT: 8091
      SPRING_PROFILES_ACTIVE: dev
    volumes:
      - ./log:/data/log
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
