CONTAINER_NAME=marketing-platform
IMAGE_NAME=system/marketing-platform-app:1.0-SNAPSHOT
HTTP_PORT=8091
DUBBO_PORT=20880
DUBBO_IP_TO_REGISTRY=111.228.17.153
NACOS_HOST=111.228.17.153
NACOS_PORT=8848

echo "容器部署开始 ${CONTAINER_NAME}"

# 停止容器
docker stop ${CONTAINER_NAME}

# 删除容器
docker rm ${CONTAINER_NAME}

# 启动容器
docker run --name ${CONTAINER_NAME} \
-p ${HTTP_PORT}:${HTTP_PORT} \
-p ${DUBBO_PORT}:${DUBBO_PORT} \
-e SPRING_PROFILES_ACTIVE=dev \
-e DUBBO_PORT=${DUBBO_PORT} \
-e DUBBO_IP_TO_REGISTRY=${DUBBO_IP_TO_REGISTRY} \
-e JAVA_OPTS="-DDUBBO_IP_TO_REGISTRY=${DUBBO_IP_TO_REGISTRY}" \
-e NACOS_HOST=${NACOS_HOST} \
-e NACOS_PORT=${NACOS_PORT} \
-d ${IMAGE_NAME}

echo "容器部署成功 ${CONTAINER_NAME}"

docker logs -f ${CONTAINER_NAME}
