server:
  port: 8091
  tomcat:
    threads:
      max: 200   # 最大线程数
      min-square: 50   # 最小线程数
    accept-count: 10   # 接受连接数
# 应用配置
app:
  config:
    # 版本，方便通过接口版本升级
    api-version: v1
    # 跨域，开发阶段可以设置为 * 不限制
    cross-origin: "*"

activity:
  order:
    bloom-filter:
      expected-insertions: 1000000
      false-probability: 0.001

# 线程池配置
thread:
  pool:
    executor:
      config:
        core-pool-size: 20
        max-pool-size: 50
        keep-alive-time: 5000
        block-queue-size: 5000
        policy: CallerRunsPolicy

# Sharding-JDBC 多数据源配置；ds0 为配置库，ds1、ds2 为用户行为分库
spring:
  shardingsphere:
    datasource:
      names: ds0,ds1,ds2
      ds0:
        type: com.zaxxer.hikari.HikariDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        jdbc-url: jdbc:mysql://111.228.17.153:13306/big_market?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai&useSSL=false
        username: root
        password: 123456
        pool-name: Retail_HikariCP_DS0
        minimum-idle: 5
        maximum-pool-size: 10
      ds1:
        type: com.zaxxer.hikari.HikariDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        jdbc-url: jdbc:mysql://111.228.17.153:13306/big_market_01?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai&useSSL=false
        username: root
        password: 123456
        pool-name: Retail_HikariCP_DS1
        minimum-idle: 5
        maximum-pool-size: 10
      ds2:
        type: com.zaxxer.hikari.HikariDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        jdbc-url: jdbc:mysql://111.228.17.153:13306/big_market_02?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai&useSSL=false
        username: root
        password: 123456
        pool-name: Retail_HikariCP_DS2
        minimum-idle: 5
        maximum-pool-size: 10
    sharding:
      default-data-source-name: ds0
      tables:
        raffle_activity_order:
          actual-data-nodes: ds$->{1..2}.raffle_activity_order_00$->{0..3}
          database-strategy:
            standard:
              sharding-column: user_id
              precise-algorithm-class-name: cn.qijiv.infrastructure.persistent.db.UserIdShardingAlgorithm
          table-strategy:
            standard:
              sharding-column: user_id
              precise-algorithm-class-name: cn.qijiv.infrastructure.persistent.db.UserIdShardingAlgorithm
        raffle_activity_account:
          actual-data-nodes: ds$->{1..2}.raffle_activity_account
          database-strategy:
            standard:
              sharding-column: user_id
              precise-algorithm-class-name: cn.qijiv.infrastructure.persistent.db.UserIdShardingAlgorithm
    props:
      sql:
        show: true

redis:
  address: redis://111.228.17.153:16379
  username: qijiv
  password: 18903705503qQ
  database: 0
  connection-pool-size: 32
  connection-minimum-idle-size: 8
  connect-timeout: 10000
  timeout: 3000

mybatis:
 mapper-locations: classpath:/mybatis/mapper/*.xml
 config-location:  classpath:/mybatis/config/mybatis-config.xml

# 日志
logging:
  level:
    root: info
  config: classpath:logback-spring.xml
